import Head from 'next/head';
import { ChangeEvent } from 'react';
import { optionType } from '../types';

type Props = {
  location: string;
  options: [];
  onInputChange: (e: ChangeEvent<HTMLInputElement>) => void;
  onOptionSelect: (option: optionType) => void;
  onSubmit: () => void;
};

export default function Search({
  location,
  options,
  onInputChange,
  onOptionSelect,
  onSubmit,
}: Props): JSX.Element {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center items-center bg-gradient-to-br from-purple-800 via-teal-500 to-violet-700 h-[100vh] w-full">
        <section className="w-full md:max-w-[500px] p-4 flex flex-col text-center items-center justify-center md:px-10 lg:p-24 h-full lg:h-[500px] bg-white bg-opacity-20 backdrop-blur-lg drop-shadow-lg rounded text-zinc-700">
          <h1 className="text-4xl font-thin">
            Weather <span className="font-black">Forecast</span>
          </h1>
          <p className="text-sm mt-2">
            Enter the place you want to know weather of and select an option
            from the dropdown
          </p>
          <div className=" relative flex mt-10 md:mt-4">
            <input
              type="text"
              value={location}
              className="px-2 py-1 rounded-l-md border-2 border-white"
              onChange={onInputChange}
            />
            <ul className="absolute top-9 bg-white ml-1 rounded-b-md">
              {options.map((option: optionType, index: number) => (
                <li key={option.name + '-' + index}>
                  <button
                    className="text-left text-sm w-full hover:bg-zinc-700 hover:text-white px-2 py-1 cursor-pointer"
                    onClick={() => onOptionSelect(option)}
                  >
                    {option.name}
                  </button>
                </li>
              ))}
            </ul>
            <button
              className="rounded-r-md border-2 border-zinc-100 hover:border-zinc-500 hover:text-zinc-500 text-zinc-100 px-2 py-1 cursor-pointer"
              onClick={onSubmit}
            >
              Search
            </button>
          </div>
        </section>
      </main>
    </>
  );
}
